name: Print Commit Message

on:
  push:
    branches:
      - master
      
jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Print commit message
        run: echo "The commit message is ${{github.event.head_commit.message}}"
    
